# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "array-back-3.1.0" = {
      name = "array-back";
      packageName = "array-back";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-back/-/array-back-3.1.0.tgz";
        sha512 = "TkuxA4UCOvxuDK6NZYXCalszEzj+TLszyASooky+i742l9TqsOdYCMJJupxRic61hwquNtppB3hgcuq9SVSH1Q==";
      };
    };
    "array-back-4.0.2" = {
      name = "array-back";
      packageName = "array-back";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-back/-/array-back-4.0.2.tgz";
        sha512 = "NbdMezxqf94cnNfWLL7V/im0Ub+Anbb0IoZhvzie8+4HJ4nMQuzHuy49FkGYCJK2yAloZ3meiB6AVMClbrI1vg==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha512 = "72fSenhMw2HZMTVHeCA9KCmpEIbzWiQsjN+BHcBbS9vr1mtt+vJjPdksIBNUmKAW8TFUDPJK5SUU3QhE9NEXDw==";
      };
    };
    "command-line-args-5.2.1" = {
      name = "command-line-args";
      packageName = "command-line-args";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/command-line-args/-/command-line-args-5.2.1.tgz";
        sha512 = "H4UfQhZyakIjC74I9d34fGYDwk3XpSr17QhEd0Q3I9Xq1CETHo4Hcuo87WyWHpAF1aSLjLRf5lD9ZGX2qStUvg==";
      };
    };
    "command-line-usage-6.1.3" = {
      name = "command-line-usage";
      packageName = "command-line-usage";
      version = "6.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/command-line-usage/-/command-line-usage-6.1.3.tgz";
        sha512 = "sH5ZSPr+7UStsloltmDh7Ce5fb8XPlHyoPzTpyyMuYCtervL65+ubVZ6Q61cFtFl62UyJlc8/JwERRbAFPUqgw==";
      };
    };
    "deep-extend-0.6.0" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.6.0.tgz";
        sha512 = "LOHxIOaPYdHlJRtCQfDIVZtfw/ufM8+rVj649RIHzcm/vGwQRXFt6OPqIFWsm2XEMrNIEtWR64sY1LEKD2vAOA==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha512 = "vbRorB5FUQWvla16U8R/qgaFIya2qGzwDrNmCZuYKrbdSUMG6I1ZCGQRefkRVhuOkIGVne7BQ35DSfo1qvJqFg==";
      };
    };
    "find-replace-3.0.0" = {
      name = "find-replace";
      packageName = "find-replace";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-replace/-/find-replace-3.0.0.tgz";
        sha512 = "6Tb2myMioCAgv5kfvP5/PkZZ/ntTpVK39fHY7WkWBgvbeE+VHd/tZuZ4mrC+bxh4cfOZeYKVPaJIZtZXV7GNCQ==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha512 = "sKJf1+ceQBr4SMkvQnBDNDtf4TXpVhVGateu0t918bl30FnbE2m4vNLX+VWe/dpjlb+HugGYzW7uQXH98HPEYw==";
      };
    };
    "lodash.camelcase-4.3.0" = {
      name = "lodash.camelcase";
      packageName = "lodash.camelcase";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.camelcase/-/lodash.camelcase-4.3.0.tgz";
        sha512 = "TwuEnCnxbc3rAvhf/LbG7tJUDzhqXyFnv3dtzLOPgCG/hODL7WFnsbwktkD7yUV0RrreP/l1PALq/YSg6VvjlA==";
      };
    };
    "reduce-flatten-2.0.0" = {
      name = "reduce-flatten";
      packageName = "reduce-flatten";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/reduce-flatten/-/reduce-flatten-2.0.0.tgz";
        sha512 = "EJ4UNY/U1t2P/2k6oqotuX2Cc3T6nxJwsM0N0asT7dhrtH1ltUxDn4NalSYmPE2rCkVpcf/X6R0wDwcFpzhd4w==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "table-layout-1.0.2" = {
      name = "table-layout";
      packageName = "table-layout";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/table-layout/-/table-layout-1.0.2.tgz";
        sha512 = "qd/R7n5rQTRFi+Zf2sk5XVVd9UQl6ZkduPFC3S7WEGJAmetDTjY3qPN50eSKzwuzEyQKy5TN2TiZdkIjos2L6A==";
      };
    };
    "typical-4.0.0" = {
      name = "typical";
      packageName = "typical";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/typical/-/typical-4.0.0.tgz";
        sha512 = "VAH4IvQ7BDFYglMd7BPRDfLgxZZX4O4TFcRDA6EN5X7erNJJq+McIEp8np9aVtxrCJ6qx4GTYVfOWNjcqwZgRw==";
      };
    };
    "typical-5.2.0" = {
      name = "typical";
      packageName = "typical";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/typical/-/typical-5.2.0.tgz";
        sha512 = "dvdQgNDNJo+8B2uBQoqdb11eUCE1JQXhvjC/CZtgvZseVd5TYMXnq0+vuUemXbd/Se29cTaUuPX3YIc2xgbvIg==";
      };
    };
    "wordwrapjs-4.0.1" = {
      name = "wordwrapjs";
      packageName = "wordwrapjs";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrapjs/-/wordwrapjs-4.0.1.tgz";
        sha512 = "kKlNACbvHrkpIw6oPeYDSmdCTu2hdMHoyXLTcUKala++lx5Y+wjJ/e474Jqv5abnVmwxw08DiTuHmw69lJGksA==";
      };
    };
  };
in
{
  "bytefield-svg-1.10.0" = nodeEnv.buildNodePackage {
    name = "bytefield-svg";
    packageName = "bytefield-svg";
    version = "1.10.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/bytefield-svg/-/bytefield-svg-1.10.0.tgz";
      sha512 = "ftT5AqRr7kxNyu/+NSciRvayoOKB/1NyvOgFqohJDq8P8Tq5NWnmlYsMMYTy6/fpXbNFCIUnEOstzoloMUuTPg==";
    };
    dependencies = [
      sources."ansi-styles-3.2.1"
      sources."array-back-3.1.0"
      sources."chalk-2.4.2"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."command-line-args-5.2.1"
      (sources."command-line-usage-6.1.3" // {
        dependencies = [
          sources."array-back-4.0.2"
          sources."typical-5.2.0"
        ];
      })
      sources."deep-extend-0.6.0"
      sources."escape-string-regexp-1.0.5"
      sources."find-replace-3.0.0"
      sources."has-flag-3.0.0"
      sources."lodash.camelcase-4.3.0"
      sources."reduce-flatten-2.0.0"
      sources."supports-color-5.5.0"
      (sources."table-layout-1.0.2" // {
        dependencies = [
          sources."array-back-4.0.2"
          sources."typical-5.2.0"
        ];
      })
      sources."typical-4.0.0"
      (sources."wordwrapjs-4.0.1" // {
        dependencies = [
          sources."typical-5.2.0"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Generate byte field diagrams in SVG format from a Clojure/EDN DSL";
      homepage = "https://github.com/Deep-Symmetry/bytefield-svg#readme";
      license = "EPL-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
