== The protocol

WARNING: This document is according to our current understanding of the
protocol and is WIP

The protocol is mostly stateless, with a stateful sub-protocol for configuration
nested within. It is an OSI 3rd layer protocol, using Ethernet II (DIX 2.0)
frames as a carrier medium. Every packet can be split into a header and a data
section, with the latter only carrying segmented image frames. Everything else
(configuration, discovery, …) is handled through the header with other protocols
muxed into it.


=== Ethernet (Physical)

The RV908M32 uses a 1000BASE-T physical medium to transfer the data. As the
sender nor the receiver cards mention specific compatibility patterns on their
respective store pages it will be further assumed that this holds true for every
LinsnLED receiver card. The current understanding is, that faster or slower
Ethernet standards are not supported at least on the RV908M32.

Our revision of the RV908M32 supports automatic MDI-X, so no crossover cable is
required for a successful communication. There is a note on the LinsnLED webpage
telling users to employ a crossover cable, so there might be boards that require
it. If it doesn't work, it is recommended to give it a try.

The RV908M32 is otherwise compatible with normal Ethernet and can be plugged
into a normal computer supporting 1000BASE-T.


=== Ethernet II frame

The data is carried in the payload section of Ethernet II (DIX 2.0) frames using
two custom *EtherTypes*, one for each sending direction. As such each EtherType
has a specific *payload* size associated with it. See <<ethertypes-length-table>>
for more details.

[[ethertypes-length-table]]
.EtherTypes employed by LinsnLED
[width=70%, align=center, cols="^2,2,3"]
|===
|EtherType|Payload Size|Description

|`0xaa55`|1472 bytes|Sender -> Receiver
|`0xaa56`|1482 bytes|Receiver -> Sender
|===

NOTE: EtherType is described as big endian.

We will be using here Ethernet II (DIX 2.0) frames in the format described by
<<ethernet-ii-packet>>. Preample and CRC can generally be ignored, as they are
automatically generated and stripped by the network hardware. If these two would
differ from the spec, the packets would not be received by the corresponding
hardware, making the protocol incompatible with standard network gear. Due to
this they will not be mentioned going forward.

[[ethernet-ii-packet]]
.Ethernet II (DIX 2.0) frame. Fields in italics are usually opaque to the user
[bytefield]
----
(def diagram-state (atom {:column 0 :y 1 :address -16 :gap? false :svg-body '()}))
(draw-column-headers)
(draw-row-header "-10")
(draw-box nil {:span 8 :borders nil})
(draw-box (text "Preample" {:font-style "italic"}) {:span 8})
(draw-box "Destination MAC" {:span 6})
(draw-box "Source MAC" {:span 6})
(draw-box "EtherType" {:span 2})
(draw-gap "Payload")
(draw-bottom)
(draw-box (text "CRC" {:font-style "italic"}) {:span 4})
----

==== MAC addressing

The *sender* does not seem to have any limitations imposed on its MAC address.
In our research the default MAC of the sender hardware was used which worked
without restrictions.

For the *receiver* this does not seem to be true. But TBD

CAUTION: *TODO* It is currently unknown which MAC the corresponding receivers use
for transfer. A single receiver uses `00:00:00:00:00:00`, but it is unknown how
this changes with more modules attached sequentially. There was also a random
MAC address by the receiver identified once in an old recording from somebody
else.

Generally the MAC address discovery happens through a specialized request /
response dynamic at the start of the transfer, further described in
<<cmd-mac-discovery>>.

=== LinsnLED Ethernet payload

This is where much of the real magic happens. Generally the Ethernet payload of
a single Ethernet packet can be split into a *32 byte header* and remainder. For
packets of EtherType `0xaa55` the remainder is *1440 bytes of frame buffer data*
(see <<frame-buffer-data>>). Whereas the current assumption is, that packets of
EtherType `0xaa56` do not make use of the 1450 byte long remainder segment
(TBD).

CAUTION: *TODO* For EtherType `0xaa56` only packets of type Mac discovery
(<<cmd-mac-discovery>>) have been discovered. There might be other messages from the
receivers for which this does not hold.

.LinsnLED Ethernet payload
[bytefield]
----
(draw-column-headers)
(draw-box "LinsnLED-Header" [{:span 16} :box-above])
(draw-box nil [{:span 16} :box-below])
(draw-gap "Remainder")
(draw-bottom)
----

[[header]]
=== The LinsnLED header

The header format is the same for both EtherTypes. It is always 32 bytes long
and can be described according to <<fig-header>>. Numbers are parsed as low
endian if not mentioned otherwise.

[[fig-header]]
.General LinsnLED Header. The fields explicitly mentioned here are always to be found
[bytefield]
----
(draw-column-headers)
(draw-box "Package ID" {:span 4})
(draw-related-boxes (repeat 4 0))
(draw-box "Cmd" {:span 1})
(draw-box nil [{:span 7} :box-above])
(draw-box "Command data (22 bytes)" [{:span 15} :box-below])
(draw-box "Chks")
----

==== Fields
[[header-field-pkgid]]
===== Package ID
This is a 4 byte LE unsigned number. For EtherType `0xaa55` it is directly tied
with the frame buffer data of the same package (see <<frame-buffer-data>>). A
frame is split into chunks and the package ID starts at zero for the first such
chunk and increments by one for each following chunk.

For EtherType `0xaa56` it has a different meaning during MAC discovery (see
<<cmd-mac-discovery>>).

===== Checksum (Chks)

The whole header except Package ID and this checksum is verified for correctness
using a *single byte* number. Assuming stem:[\text{header}[n\]] is the `n`-th
byte of the 32 byte header and using stem:[X_8] to mark the number as an eight
bit register using two's-complement for conversion, the checksum is calculated
with:

[stem]
++++
\sigma_{checksum} = \left(-\sum_{i=4}^{31} \text{header}[i]\right)_8
++++

[[header-field-cmd]]
===== Command (Cmd)

Command is a *single byte* field. So far three possible values are known. The
corresponding value changes the way the command data field must be interpreted.
This is detailed in the corresponding sections. See <<header-field-cmd-table>>
for a list, description and reference of each.

[[header-field-cmd-table]]
.All currently known command field values
[cols="^1,6,2"]
|===
|Value|Description|Reference

|`0x96`|Used to announce MAC addresses|See <<cmd-mac-discovery>>
|`0x61`|Used to transfer configuration data to a receiver|See
<<cmd-configuration>>
|`0x00`|Indicates that the header is mostly zeros. (most common one)|See
below
|===

The cmd value `0x00` is special as it is the nothing command. The command data
field (and panel index) will be filled with zeros presumably because they will
not carry any information. It is by far the most common one, as it is the
default command used during frame transfers.

===== Command Data
See Cmd field (<<header-field-cmd>>).

[[frame-buffer-data]]
=== Frame buffer data

This is *exclusively* used by the sender (EtherType `0xaa55`) and is always *1440
bytes* long. So far it seems to be the only remainder type supported. (TBD)

As a single frame does not fit into the 1440 byte payload, instead it is split
up and transferred in chunks of the same size. The data is stitched together
according to the xref:header-field-pkgid[segment number attribute] in the header,
whereby a 1440 byte long chunk starts at offset `1440 byte * segment-number` in
the final frame.

The image generally has the form of 1024 * 512 px and can be split into 512 *
512 px sub-images (left and right). Left always seems to contain an image,
whereas the right side has been observed with and without an image. No image
here means that it was filled with zeros. Interestingly the first image row was
always filled with zeros so far, the purpose of that is unknown. The only
observed encoding was uncompressed 24 bit GBR (green/blue/red) data.

CAUTION: *TODO* There are a lot of unknowns about this part currently,
especially how it is configured / announced to the receiver what the exact data
layout is. As mentioned above 24 bit GBR has been observed, but it is known that
our receiver is theoretically capable of 12 bit HDR and that other channel
orders might be possible. Currently there is no information available how this
would present itself in the data.

.Schematic example data chunk for frame buffer including LinsnLED header using zero command
[bytefield]
----
(draw-column-headers)
(draw-box "Package ID" {:span 4})
(draw-padding 32)
(doseq [val (range 5)]
  (draw-box (text "GG" :hex) [:box-first {:fill "#CCFFCC"}])
  (draw-box (text "BB" :hex) [:box-related {:fill "#CCCCFF"}])
  (draw-box (text "RR" :hex) [:box-last {:fill "#FFCCCC"}])
)
(draw-box "..." {:borders nil})
----

[[cmd-mac-discovery]]
=== MAC discovery

During a usual protocol cycle there are two places where this command type is
being used. LinsnLED sender applications use it *during the "initialization"
phase* to discover the MAC addresses of all attached receiver modules. Later on
this command is employed *to mark the start of a new frame*. The receiver always
answers (described in <<cmd-mac-discovery-recv>>).

The biggest difference between these two use-cases is the receiver MAC address.
For the general discovery of receivers the packet is broadcast, whereas later on
it is addressed at a specific module. For the broadcasted packages the content
of the remainder / frame buffer data seems to be irrelevant.

==== Data layout

The exact interpretation of the data segment is currently unknown. There is a
long non-zero segment whose value has not changed in observed transfers, so the
exact meaning is unknown. Current naive assumption is that it is just a static
piece of data. At the end one can find the 6 byte long MAC address of the
sender.

.MAC discovery packet header. Exact meaning for the highlighted part is unknown. Assumed to be static [TBD]
[bytefield]
----
(draw-column-headers)
(draw-box "Package ID" {:span 4})
(draw-related-boxes (repeat 4 0))
(draw-box 0x96)
(draw-related-boxes [0x00 0x00 0x00 0x85 0x1f 0xff 0xff 0xff 0xff 0x00 0x00 0x00
0x00 0x00 0x00 0x00] {:fill "#edc4ee"})
(draw-box "Sender MAC" {:span 6})
(draw-box "Chks")
----

CAUTION: *TODO* It is very unlike the current understanding of the protocol that
there are (relatively long) segments of data which are void of any meaning. So
be on the lookout for anything weird going on here, it could help the RE
process.

[[cmd-mac-discovery-recv]]
==== Receiver packet

The answer by the receiver is very different. It still adheres to the general
header data layout as described in <<header>>, but the *meaning of the packet ID
field changes* a bit. The command byte is zero.

As the observed value so far is relatively high, it could describe the maximum
supported package ID, the maximum buffer storage capacity, …. TBD

The remainder segment seems to be irrelevant in this case.

CAUTION: *TODO* Unknown what the packet ID field does in this case.

[[cmd-configuration]]
=== Configuring the system

CAUTION: This section is currently under heavy construction as it is one of the
more complex to RE and extensive elements of the protocol.

===== Panel Index
This is a 2 byte LE unsigned number, which describes the panel that is being
addressed during configuration. The value is otherwise 0.

CAUTION: *TODO* I think this wasn't panel, but receiver. Needs to be
investigated.

