name: Generate Doc PDF - Nightly

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          tags: my-asciidoctor-image:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
      - name: Run build
        uses: addnab/docker-run-action@v3
        with:
          image: my-asciidoctor-image:latest
          options: -v ${{ github.workspace }}:/documents/
          run: |
            echo "Running build"
            make pdf BUILD_DIR=ghbuild
      - name: Test
        run: pwd && echo "${{ github.workspace }}" && ls *
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF file
          path: ghbuild/linsnled-protocol.pdf
          retention-days: 5
      - name: Remove nightly tag before recreating it
        run:
          gh release delete nightly --cleanup-tag --yes
      - name: Create nightly release
        uses: softprops/action-gh-release@v2
        with:
          name: nightly
          tag_name: nightly
          body: From ${{ github.sha }}
          prerelease: true
          fail_on_unmatched_files: true
          files: ghbuild/linsnled-protocol.pdf
